apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flaskapp
  namespace: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flaskapp
  template:
    metadata:
      labels:
        app: python-flaskapp
    spec:
      containers:
      - name: python-flaskapp
        image: mnavarrodocker/python-flaskapp:afbdf9d
        ports:
        - containerPort: 5000
